#!/bin/sh
SHELL_FOLDER=$(dirname "$0")
. $SHELL_FOLDER/logger.sh

for branch in $(git branch --all | grep '^\s*remotes' | egrep --invert-match '(:?HEAD|master)$'); do
    git branch --track "${branch##*/}" "$branch"
done
git pull
git checkout master
