#!/bin/sh
SHELL_FOLDER=$(dirname "$0")
. $SHELL_FOLDER/logger.sh

for i in $(dir); do
    (
        info "[$i]==============>"
        cd "$i" || continue
        for remote in $(git branch -r | grep -v '\->'); do
            info "[$remote]------------>"
            git branch --track "${remote#origin/}" "$remote"
            git fetch --all
            git pull --all
        done
    )
done
